/*
 * Copyright (C) 2022 Nikolas Koesling <nikolas@koesling.info>.
 * This program is free software. You can redistribute it and/or modify it under the terms of the MIT License.
 */

#include "license.hpp"

void print_licenses(std::ostream &o) {
    o << "This Application (" << PROJECT_NAME << ' ' << PROJECT_VERSION "): " << std::endl;
    o << std::endl;
    o << "    MIT License" << std::endl;
    o << std::endl;
    o << "    Copyright (c) 2021-2022 Nikolas Koesling" << std::endl;
    o << std::endl;
    o << "    Permission is hereby granted, free of charge, to any person obtaining a copy" << std::endl;
    o << "    of this software and associated documentation files (the \"Software\"), to deal" << std::endl;
    o << "    in the Software without restriction, including without limitation the rights" << std::endl;
    o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" << std::endl;
    o << "    copies of the Software, and to permit persons to whom the Software is" << std::endl;
    o << "    furnished to do so, subject to the following conditions:" << std::endl;
    o << std::endl;
    o << "    The above copyright notice and this permission notice shall be included in all" << std::endl;
    o << "    copies or substantial portions of the Software." << std::endl;
    o << std::endl;
    o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" << std::endl;
    o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," << std::endl;
    o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" << std::endl;
    o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" << std::endl;
    o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," << std::endl;
    o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE" << std::endl;
    o << "    SOFTWARE." << std::endl;
    o << std::endl;
    o << std::endl;
    o << "cxxopts Library (https://github.com/jarro2783/cxxopts)" << std::endl;
    o << std::endl;
    o << "    MIT License" << std::endl;
    o << std::endl;
    o << "    Copyright (c) 2014 Jarryd Beck" << std::endl;
    o << std::endl;
    o << "    Permission is hereby granted, free of charge, to any person obtaining a copy" << std::endl;
    o << "    of this software and associated documentation files (the \"Software\"), to deal" << std::endl;
    o << "    in the Software without restriction, including without limitation the rights" << std::endl;
    o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" << std::endl;
    o << "    copies of the Software, and to permit persons to whom the Software is" << std::endl;
    o << "    furnished to do so, subject to the following conditions:" << std::endl;
    o << std::endl;
    o << "    The above copyright notice and this permission notice shall be included in" << std::endl;
    o << "    all copies or substantial portions of the Software." << std::endl;
    o << std::endl;
    o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" << std::endl;
    o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," << std::endl;
    o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" << std::endl;
    o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" << std::endl;
    o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," << std::endl;
    o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN" << std::endl;
    o << "    THE SOFTWARE." << std::endl;
    o << std::endl;
    o << std::endl;
    o << "cxxshm Library (https://github.com/NikolasK-source/cxxshm)" << std::endl;
    o << std::endl;
    o << "    MIT License" << std::endl;
    o << std::endl;
    o << "    Copyright (c) 2022 Nikolas Koesling" << std::endl;
    o << std::endl;
    o << "    Permission is hereby granted, free of charge, to any person obtaining a copy" << std::endl;
    o << "    of this software and associated documentation files (the \"Software\"), to deal" << std::endl;
    o << "    in the Software without restriction, including without limitation the rights" << std::endl;
    o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" << std::endl;
    o << "    copies of the Software, and to permit persons to whom the Software is" << std::endl;
    o << "    furnished to do so, subject to the following conditions:" << std::endl;
    o << std::endl;
    o << "    The above copyright notice and this permission notice shall be included in all" << std::endl;
    o << "    copies or substantial portions of the Software." << std::endl;
    o << std::endl;
    o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" << std::endl;
    o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," << std::endl;
    o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" << std::endl;
    o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" << std::endl;
    o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," << std::endl;
    o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE" << std::endl;
    o << "    SOFTWARE." << std::endl;
    o << std::endl;
    o << std::endl;
    o << "cxxendian Library (https://github.com/NikolasK-source/cxxendian)" << std::endl;
    o << std::endl;
    o << "    MIT License" << std::endl;
    o << std::endl;
    o << "    Copyright (c) 2022 Nikolas Koesling" << std::endl;
    o << std::endl;
    o << "    Permission is hereby granted, free of charge, to any person obtaining a copy" << std::endl;
    o << "    of this software and associated documentation files (the \"Software\"), to deal" << std::endl;
    o << "    in the Software without restriction, including without limitation the rights" << std::endl;
    o << "    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" << std::endl;
    o << "    copies of the Software, and to permit persons to whom the Software is" << std::endl;
    o << "    furnished to do so, subject to the following conditions:" << std::endl;
    o << std::endl;
    o << "    The above copyright notice and this permission notice shall be included in all" << std::endl;
    o << "    copies or substantial portions of the Software." << std::endl;
    o << std::endl;
    o << "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" << std::endl;
    o << "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," << std::endl;
    o << "    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" << std::endl;
    o << "    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" << std::endl;
    o << "    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," << std::endl;
    o << "    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE" << std::endl;
    o << "    SOFTWARE." << std::endl;
    o << std::endl;
    o << std::endl;
    o << "GNU Readline Library (http://git.savannah.gnu.org/cgit/readline.git/)";
    o << std::endl;
    o << "                        GNU GENERAL PUBLIC LICENSE" << std::endl;
    o << "                           Version 3, 29 June 2007" << std::endl;
    o << std::endl;
    o << "     Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>" << std::endl;
    o << "     Everyone is permitted to copy and distribute verbatim copies" << std::endl;
    o << "     of this license document, but changing it is not allowed." << std::endl;
    o << std::endl;
    o << "                                Preamble" << std::endl;
    o << std::endl;
    o << "      The GNU General Public License is a free, copyleft license for" << std::endl;
    o << "    software and other kinds of works." << std::endl;
    o << std::endl;
    o << "      The licenses for most software and other practical works are designed" << std::endl;
    o << "    to take away your freedom to share and change the works.  By contrast," << std::endl;
    o << "    the GNU General Public License is intended to guarantee your freedom to" << std::endl;
    o << "    share and change all versions of a program--to make sure it remains free" << std::endl;
    o << "    software for all its users.  We, the Free Software Foundation, use the" << std::endl;
    o << "    GNU General Public License for most of our software; it applies also to" << std::endl;
    o << "    any other work released this way by its authors.  You can apply it to" << std::endl;
    o << "    your programs, too." << std::endl;
    o << std::endl;
    o << "      When we speak of free software, we are referring to freedom, not" << std::endl;
    o << "    price.  Our General Public Licenses are designed to make sure that you" << std::endl;
    o << "    have the freedom to distribute copies of free software (and charge for" << std::endl;
    o << "    them if you wish), that you receive source code or can get it if you" << std::endl;
    o << "    want it, that you can change the software or use pieces of it in new" << std::endl;
    o << "    free programs, and that you know you can do these things." << std::endl;
    o << std::endl;
    o << "      To protect your rights, we need to prevent others from denying you" << std::endl;
    o << "    these rights or asking you to surrender the rights.  Therefore, you have" << std::endl;
    o << "    certain responsibilities if you distribute copies of the software, or if" << std::endl;
    o << "    you modify it: responsibilities to respect the freedom of others." << std::endl;
    o << std::endl;
    o << "      For example, if you distribute copies of such a program, whether" << std::endl;
    o << "    gratis or for a fee, you must pass on to the recipients the same" << std::endl;
    o << "    freedoms that you received.  You must make sure that they, too, receive" << std::endl;
    o << "    or can get the source code.  And you must show them these terms so they" << std::endl;
    o << "    know their rights." << std::endl;
    o << std::endl;
    o << "      Developers that use the GNU GPL protect your rights with two steps:" << std::endl;
    o << "    (1) assert copyright on the software, and (2) offer you this License" << std::endl;
    o << "    giving you legal permission to copy, distribute and/or modify it." << std::endl;
    o << std::endl;
    o << "      For the developers' and authors' protection, the GPL clearly explains" << std::endl;
    o << "    that there is no warranty for this free software.  For both users' and" << std::endl;
    o << "    authors' sake, the GPL requires that modified versions be marked as" << std::endl;
    o << "    changed, so that their problems will not be attributed erroneously to" << std::endl;
    o << "    authors of previous versions." << std::endl;
    o << std::endl;
    o << "      Some devices are designed to deny users access to install or run" << std::endl;
    o << "    modified versions of the software inside them, although the manufacturer" << std::endl;
    o << "    can do so.  This is fundamentally incompatible with the aim of" << std::endl;
    o << "    protecting users' freedom to change the software.  The systematic" << std::endl;
    o << "    pattern of such abuse occurs in the area of products for individuals to" << std::endl;
    o << "    use, which is precisely where it is most unacceptable.  Therefore, we" << std::endl;
    o << "    have designed this version of the GPL to prohibit the practice for those" << std::endl;
    o << "    products.  If such problems arise substantially in other domains, we" << std::endl;
    o << "    stand ready to extend this provision to those domains in future versions" << std::endl;
    o << "    of the GPL, as needed to protect the freedom of users." << std::endl;
    o << std::endl;
    o << "      Finally, every program is threatened constantly by software patents." << std::endl;
    o << "    States should not allow patents to restrict development and use of" << std::endl;
    o << "    software on general-purpose computers, but in those that do, we wish to" << std::endl;
    o << "    avoid the special danger that patents applied to a free program could" << std::endl;
    o << "    make it effectively proprietary.  To prevent this, the GPL assures that" << std::endl;
    o << "    patents cannot be used to render the program non-free." << std::endl;
    o << std::endl;
    o << "      The precise terms and conditions for copying, distribution and" << std::endl;
    o << "    modification follow." << std::endl;
    o << std::endl;
    o << "                           TERMS AND CONDITIONS" << std::endl;
    o << std::endl;
    o << "      0. Definitions." << std::endl;
    o << std::endl;
    o << "      \"This License\" refers to version 3 of the GNU General Public License." << std::endl;
    o << std::endl;
    o << "      \"Copyright\" also means copyright-like laws that apply to other kinds of" << std::endl;
    o << "    works, such as semiconductor masks." << std::endl;
    o << std::endl;
    o << "      \"The Program\" refers to any copyrightable work licensed under this" << std::endl;
    o << "    License.  Each licensee is addressed as \"you\".  \"Licensees\" and" << std::endl;
    o << "    \"recipients\" may be individuals or organizations." << std::endl;
    o << std::endl;
    o << "      To \"modify\" a work means to copy from or adapt all or part of the work" << std::endl;
    o << "    in a fashion requiring copyright permission, other than the making of an" << std::endl;
    o << "    exact copy.  The resulting work is called a \"modified version\" of the" << std::endl;
    o << "    earlier work or a work \"based on\" the earlier work." << std::endl;
    o << std::endl;
    o << "      A \"covered work\" means either the unmodified Program or a work based" << std::endl;
    o << "    on the Program." << std::endl;
    o << std::endl;
    o << "      To \"propagate\" a work means to do anything with it that, without" << std::endl;
    o << "    permission, would make you directly or secondarily liable for" << std::endl;
    o << "    infringement under applicable copyright law, except executing it on a" << std::endl;
    o << "    computer or modifying a private copy.  Propagation includes copying," << std::endl;
    o << "    distribution (with or without modification), making available to the" << std::endl;
    o << "    public, and in some countries other activities as well." << std::endl;
    o << std::endl;
    o << "      To \"convey\" a work means any kind of propagation that enables other" << std::endl;
    o << "    parties to make or receive copies.  Mere interaction with a user through" << std::endl;
    o << "    a computer network, with no transfer of a copy, is not conveying." << std::endl;
    o << std::endl;
    o << "      An interactive user interface displays \"Appropriate Legal Notices\"" << std::endl;
    o << "    to the extent that it includes a convenient and prominently visible" << std::endl;
    o << "    feature that (1) displays an appropriate copyright notice, and (2)" << std::endl;
    o << "    tells the user that there is no warranty for the work (except to the" << std::endl;
    o << "    extent that warranties are provided), that licensees may convey the" << std::endl;
    o << "    work under this License, and how to view a copy of this License.  If" << std::endl;
    o << "    the interface presents a list of user commands or options, such as a" << std::endl;
    o << "    menu, a prominent item in the list meets this criterion." << std::endl;
    o << std::endl;
    o << "      1. Source Code." << std::endl;
    o << std::endl;
    o << "      The \"source code\" for a work means the preferred form of the work" << std::endl;
    o << "    for making modifications to it.  \"Object code\" means any non-source" << std::endl;
    o << "    form of a work." << std::endl;
    o << std::endl;
    o << "      A \"Standard Interface\" means an interface that either is an official" << std::endl;
    o << "    standard defined by a recognized standards body, or, in the case of" << std::endl;
    o << "    interfaces specified for a particular programming language, one that" << std::endl;
    o << "    is widely used among developers working in that language." << std::endl;
    o << std::endl;
    o << "      The \"System Libraries\" of an executable work include anything, other" << std::endl;
    o << "    than the work as a whole, that (a) is included in the normal form of" << std::endl;
    o << "    packaging a Major Component, but which is not part of that Major" << std::endl;
    o << "    Component, and (b) serves only to enable use of the work with that" << std::endl;
    o << "    Major Component, or to implement a Standard Interface for which an" << std::endl;
    o << "    implementation is available to the public in source code form.  A" << std::endl;
    o << "    \"Major Component\", in this context, means a major essential component" << std::endl;
    o << "    (kernel, window system, and so on) of the specific operating system" << std::endl;
    o << "    (if any) on which the executable work runs, or a compiler used to" << std::endl;
    o << "    produce the work, or an object code interpreter used to run it." << std::endl;
    o << std::endl;
    o << "      The \"Corresponding Source\" for a work in object code form means all" << std::endl;
    o << "    the source code needed to generate, install, and (for an executable" << std::endl;
    o << "    work) run the object code and to modify the work, including scripts to" << std::endl;
    o << "    control those activities.  However, it does not include the work's" << std::endl;
    o << "    System Libraries, or general-purpose tools or generally available free" << std::endl;
    o << "    programs which are used unmodified in performing those activities but" << std::endl;
    o << "    which are not part of the work.  For example, Corresponding Source" << std::endl;
    o << "    includes interface definition files associated with source files for" << std::endl;
    o << "    the work, and the source code for shared libraries and dynamically" << std::endl;
    o << "    linked subprograms that the work is specifically designed to require," << std::endl;
    o << "    such as by intimate data communication or control flow between those" << std::endl;
    o << "    subprograms and other parts of the work." << std::endl;
    o << std::endl;
    o << "      The Corresponding Source need not include anything that users" << std::endl;
    o << "    can regenerate automatically from other parts of the Corresponding" << std::endl;
    o << "    Source." << std::endl;
    o << std::endl;
    o << "      The Corresponding Source for a work in source code form is that" << std::endl;
    o << "    same work." << std::endl;
    o << std::endl;
    o << "      2. Basic Permissions." << std::endl;
    o << std::endl;
    o << "      All rights granted under this License are granted for the term of" << std::endl;
    o << "    copyright on the Program, and are irrevocable provided the stated" << std::endl;
    o << "    conditions are met.  This License explicitly affirms your unlimited" << std::endl;
    o << "    permission to run the unmodified Program.  The output from running a" << std::endl;
    o << "    covered work is covered by this License only if the output, given its" << std::endl;
    o << "    content, constitutes a covered work.  This License acknowledges your" << std::endl;
    o << "    rights of fair use or other equivalent, as provided by copyright law." << std::endl;
    o << std::endl;
    o << "      You may make, run and propagate covered works that you do not" << std::endl;
    o << "    convey, without conditions so long as your license otherwise remains" << std::endl;
    o << "    in force.  You may convey covered works to others for the sole purpose" << std::endl;
    o << "    of having them make modifications exclusively for you, or provide you" << std::endl;
    o << "    with facilities for running those works, provided that you comply with" << std::endl;
    o << "    the terms of this License in conveying all material for which you do" << std::endl;
    o << "    not control copyright.  Those thus making or running the covered works" << std::endl;
    o << "    for you must do so exclusively on your behalf, under your direction" << std::endl;
    o << "    and control, on terms that prohibit them from making any copies of" << std::endl;
    o << "    your copyrighted material outside their relationship with you." << std::endl;
    o << std::endl;
    o << "      Conveying under any other circumstances is permitted solely under" << std::endl;
    o << "    the conditions stated below.  Sublicensing is not allowed; section 10" << std::endl;
    o << "    makes it unnecessary." << std::endl;
    o << std::endl;
    o << "      3. Protecting Users' Legal Rights From Anti-Circumvention Law." << std::endl;
    o << std::endl;
    o << "      No covered work shall be deemed part of an effective technological" << std::endl;
    o << "    measure under any applicable law fulfilling obligations under article" << std::endl;
    o << "    11 of the WIPO copyright treaty adopted on 20 December 1996, or" << std::endl;
    o << "    similar laws prohibiting or restricting circumvention of such" << std::endl;
    o << "    measures." << std::endl;
    o << std::endl;
    o << "      When you convey a covered work, you waive any legal power to forbid" << std::endl;
    o << "    circumvention of technological measures to the extent such circumvention" << std::endl;
    o << "    is effected by exercising rights under this License with respect to" << std::endl;
    o << "    the covered work, and you disclaim any intention to limit operation or" << std::endl;
    o << "    modification of the work as a means of enforcing, against the work's" << std::endl;
    o << "    users, your or third parties' legal rights to forbid circumvention of" << std::endl;
    o << "    technological measures." << std::endl;
    o << std::endl;
    o << "      4. Conveying Verbatim Copies." << std::endl;
    o << std::endl;
    o << "      You may convey verbatim copies of the Program's source code as you" << std::endl;
    o << "    receive it, in any medium, provided that you conspicuously and" << std::endl;
    o << "    appropriately publish on each copy an appropriate copyright notice;" << std::endl;
    o << "    keep intact all notices stating that this License and any" << std::endl;
    o << "    non-permissive terms added in accord with section 7 apply to the code;" << std::endl;
    o << "    keep intact all notices of the absence of any warranty; and give all" << std::endl;
    o << "    recipients a copy of this License along with the Program." << std::endl;
    o << std::endl;
    o << "      You may charge any price or no price for each copy that you convey," << std::endl;
    o << "    and you may offer support or warranty protection for a fee." << std::endl;
    o << std::endl;
    o << "      5. Conveying Modified Source Versions." << std::endl;
    o << std::endl;
    o << "      You may convey a work based on the Program, or the modifications to" << std::endl;
    o << "    produce it from the Program, in the form of source code under the" << std::endl;
    o << "    terms of section 4, provided that you also meet all of these conditions:" << std::endl;
    o << std::endl;
    o << "        a) The work must carry prominent notices stating that you modified" << std::endl;
    o << "        it, and giving a relevant date." << std::endl;
    o << std::endl;
    o << "        b) The work must carry prominent notices stating that it is" << std::endl;
    o << "        released under this License and any conditions added under section" << std::endl;
    o << "        7.  This requirement modifies the requirement in section 4 to" << std::endl;
    o << "        \"keep intact all notices\"." << std::endl;
    o << std::endl;
    o << "        c) You must license the entire work, as a whole, under this" << std::endl;
    o << "        License to anyone who comes into possession of a copy.  This" << std::endl;
    o << "        License will therefore apply, along with any applicable section 7" << std::endl;
    o << "        additional terms, to the whole of the work, and all its parts," << std::endl;
    o << "        regardless of how they are packaged.  This License gives no" << std::endl;
    o << "        permission to license the work in any other way, but it does not" << std::endl;
    o << "        invalidate such permission if you have separately received it." << std::endl;
    o << std::endl;
    o << "        d) If the work has interactive user interfaces, each must display" << std::endl;
    o << "        Appropriate Legal Notices; however, if the Program has interactive" << std::endl;
    o << "        interfaces that do not display Appropriate Legal Notices, your" << std::endl;
    o << "        work need not make them do so." << std::endl;
    o << std::endl;
    o << "      A compilation of a covered work with other separate and independent" << std::endl;
    o << "    works, which are not by their nature extensions of the covered work," << std::endl;
    o << "    and which are not combined with it such as to form a larger program," << std::endl;
    o << "    in or on a volume of a storage or distribution medium, is called an" << std::endl;
    o << "    \"aggregate\" if the compilation and its resulting copyright are not" << std::endl;
    o << "    used to limit the access or legal rights of the compilation's users" << std::endl;
    o << "    beyond what the individual works permit.  Inclusion of a covered work" << std::endl;
    o << "    in an aggregate does not cause this License to apply to the other" << std::endl;
    o << "    parts of the aggregate." << std::endl;
    o << std::endl;
    o << "      6. Conveying Non-Source Forms." << std::endl;
    o << std::endl;
    o << "      You may convey a covered work in object code form under the terms" << std::endl;
    o << "    of sections 4 and 5, provided that you also convey the" << std::endl;
    o << "    machine-readable Corresponding Source under the terms of this License," << std::endl;
    o << "    in one of these ways:" << std::endl;
    o << std::endl;
    o << "        a) Convey the object code in, or embodied in, a physical product" << std::endl;
    o << "        (including a physical distribution medium), accompanied by the" << std::endl;
    o << "        Corresponding Source fixed on a durable physical medium" << std::endl;
    o << "        customarily used for software interchange." << std::endl;
    o << std::endl;
    o << "        b) Convey the object code in, or embodied in, a physical product" << std::endl;
    o << "        (including a physical distribution medium), accompanied by a" << std::endl;
    o << "        written offer, valid for at least three years and valid for as" << std::endl;
    o << "        long as you offer spare parts or customer support for that product" << std::endl;
    o << "        model, to give anyone who possesses the object code either (1) a" << std::endl;
    o << "        copy of the Corresponding Source for all the software in the" << std::endl;
    o << "        product that is covered by this License, on a durable physical" << std::endl;
    o << "        medium customarily used for software interchange, for a price no" << std::endl;
    o << "        more than your reasonable cost of physically performing this" << std::endl;
    o << "        conveying of source, or (2) access to copy the" << std::endl;
    o << "        Corresponding Source from a network server at no charge." << std::endl;
    o << std::endl;
    o << "        c) Convey individual copies of the object code with a copy of the" << std::endl;
    o << "        written offer to provide the Corresponding Source.  This" << std::endl;
    o << "        alternative is allowed only occasionally and noncommercially, and" << std::endl;
    o << "        only if you received the object code with such an offer, in accord" << std::endl;
    o << "        with subsection 6b." << std::endl;
    o << std::endl;
    o << "        d) Convey the object code by offering access from a designated" << std::endl;
    o << "        place (gratis or for a charge), and offer equivalent access to the" << std::endl;
    o << "        Corresponding Source in the same way through the same place at no" << std::endl;
    o << "        further charge.  You need not require recipients to copy the" << std::endl;
    o << "        Corresponding Source along with the object code.  If the place to" << std::endl;
    o << "        copy the object code is a network server, the Corresponding Source" << std::endl;
    o << "        may be on a different server (operated by you or a third party)" << std::endl;
    o << "        that supports equivalent copying facilities, provided you maintain" << std::endl;
    o << "        clear directions next to the object code saying where to find the" << std::endl;
    o << "        Corresponding Source.  Regardless of what server hosts the" << std::endl;
    o << "        Corresponding Source, you remain obligated to ensure that it is" << std::endl;
    o << "        available for as long as needed to satisfy these requirements." << std::endl;
    o << std::endl;
    o << "        e) Convey the object code using peer-to-peer transmission, provided" << std::endl;
    o << "        you inform other peers where the object code and Corresponding" << std::endl;
    o << "        Source of the work are being offered to the general public at no" << std::endl;
    o << "        charge under subsection 6d." << std::endl;
    o << std::endl;
    o << "      A separable portion of the object code, whose source code is excluded" << std::endl;
    o << "    from the Corresponding Source as a System Library, need not be" << std::endl;
    o << "    included in conveying the object code work." << std::endl;
    o << std::endl;
    o << "      A \"User Product\" is either (1) a \"consumer product\", which means any" << std::endl;
    o << "    tangible personal property which is normally used for personal, family," << std::endl;
    o << "    or household purposes, or (2) anything designed or sold for incorporation" << std::endl;
    o << "    into a dwelling.  In determining whether a product is a consumer product," << std::endl;
    o << "    doubtful cases shall be resolved in favor of coverage.  For a particular" << std::endl;
    o << "    product received by a particular user, \"normally used\" refers to a" << std::endl;
    o << "    typical or common use of that class of product, regardless of the status" << std::endl;
    o << "    of the particular user or of the way in which the particular user" << std::endl;
    o << "    actually uses, or expects or is expected to use, the product.  A product" << std::endl;
    o << "    is a consumer product regardless of whether the product has substantial" << std::endl;
    o << "    commercial, industrial or non-consumer uses, unless such uses represent" << std::endl;
    o << "    the only significant mode of use of the product." << std::endl;
    o << std::endl;
    o << "      \"Installation Information\" for a User Product means any methods," << std::endl;
    o << "    procedures, authorization keys, or other information required to install" << std::endl;
    o << "    and execute modified versions of a covered work in that User Product from" << std::endl;
    o << "    a modified version of its Corresponding Source.  The information must" << std::endl;
    o << "    suffice to ensure that the continued functioning of the modified object" << std::endl;
    o << "    code is in no case prevented or interfered with solely because" << std::endl;
    o << "    modification has been made." << std::endl;
    o << std::endl;
    o << "      If you convey an object code work under this section in, or with, or" << std::endl;
    o << "    specifically for use in, a User Product, and the conveying occurs as" << std::endl;
    o << "    part of a transaction in which the right of possession and use of the" << std::endl;
    o << "    User Product is transferred to the recipient in perpetuity or for a" << std::endl;
    o << "    fixed term (regardless of how the transaction is characterized), the" << std::endl;
    o << "    Corresponding Source conveyed under this section must be accompanied" << std::endl;
    o << "    by the Installation Information.  But this requirement does not apply" << std::endl;
    o << "    if neither you nor any third party retains the ability to install" << std::endl;
    o << "    modified object code on the User Product (for example, the work has" << std::endl;
    o << "    been installed in ROM)." << std::endl;
    o << std::endl;
    o << "      The requirement to provide Installation Information does not include a" << std::endl;
    o << "    requirement to continue to provide support service, warranty, or updates" << std::endl;
    o << "    for a work that has been modified or installed by the recipient, or for" << std::endl;
    o << "    the User Product in which it has been modified or installed.  Access to a" << std::endl;
    o << "    network may be denied when the modification itself materially and" << std::endl;
    o << "    adversely affects the operation of the network or violates the rules and" << std::endl;
    o << "    protocols for communication across the network." << std::endl;
    o << std::endl;
    o << "      Corresponding Source conveyed, and Installation Information provided," << std::endl;
    o << "    in accord with this section must be in a format that is publicly" << std::endl;
    o << "    documented (and with an implementation available to the public in" << std::endl;
    o << "    source code form), and must require no special password or key for" << std::endl;
    o << "    unpacking, reading or copying." << std::endl;
    o << std::endl;
    o << "      7. Additional Terms." << std::endl;
    o << std::endl;
    o << "      \"Additional permissions\" are terms that supplement the terms of this" << std::endl;
    o << "    License by making exceptions from one or more of its conditions." << std::endl;
    o << "    Additional permissions that are applicable to the entire Program shall" << std::endl;
    o << "    be treated as though they were included in this License, to the extent" << std::endl;
    o << "    that they are valid under applicable law.  If additional permissions" << std::endl;
    o << "    apply only to part of the Program, that part may be used separately" << std::endl;
    o << "    under those permissions, but the entire Program remains governed by" << std::endl;
    o << "    this License without regard to the additional permissions." << std::endl;
    o << std::endl;
    o << "      When you convey a copy of a covered work, you may at your option" << std::endl;
    o << "    remove any additional permissions from that copy, or from any part of" << std::endl;
    o << "    it.  (Additional permissions may be written to require their own" << std::endl;
    o << "    removal in certain cases when you modify the work.)  You may place" << std::endl;
    o << "    additional permissions on material, added by you to a covered work," << std::endl;
    o << "    for which you have or can give appropriate copyright permission." << std::endl;
    o << std::endl;
    o << "      Notwithstanding any other provision of this License, for material you" << std::endl;
    o << "    add to a covered work, you may (if authorized by the copyright holders of" << std::endl;
    o << "    that material) supplement the terms of this License with terms:" << std::endl;
    o << std::endl;
    o << "        a) Disclaiming warranty or limiting liability differently from the" << std::endl;
    o << "        terms of sections 15 and 16 of this License; or" << std::endl;
    o << std::endl;
    o << "        b) Requiring preservation of specified reasonable legal notices or" << std::endl;
    o << "        author attributions in that material or in the Appropriate Legal" << std::endl;
    o << "        Notices displayed by works containing it; or" << std::endl;
    o << std::endl;
    o << "        c) Prohibiting misrepresentation of the origin of that material, or" << std::endl;
    o << "        requiring that modified versions of such material be marked in" << std::endl;
    o << "        reasonable ways as different from the original version; or" << std::endl;
    o << std::endl;
    o << "        d) Limiting the use for publicity purposes of names of licensors or" << std::endl;
    o << "        authors of the material; or" << std::endl;
    o << std::endl;
    o << "        e) Declining to grant rights under trademark law for use of some" << std::endl;
    o << "        trade names, trademarks, or service marks; or" << std::endl;
    o << std::endl;
    o << "        f) Requiring indemnification of licensors and authors of that" << std::endl;
    o << "        material by anyone who conveys the material (or modified versions of" << std::endl;
    o << "        it) with contractual assumptions of liability to the recipient, for" << std::endl;
    o << "        any liability that these contractual assumptions directly impose on" << std::endl;
    o << "        those licensors and authors." << std::endl;
    o << std::endl;
    o << "      All other non-permissive additional terms are considered \"further" << std::endl;
    o << "    restrictions\" within the meaning of section 10.  If the Program as you" << std::endl;
    o << "    received it, or any part of it, contains a notice stating that it is" << std::endl;
    o << "    governed by this License along with a term that is a further" << std::endl;
    o << "    restriction, you may remove that term.  If a license document contains" << std::endl;
    o << "    a further restriction but permits relicensing or conveying under this" << std::endl;
    o << "    License, you may add to a covered work material governed by the terms" << std::endl;
    o << "    of that license document, provided that the further restriction does" << std::endl;
    o << "    not survive such relicensing or conveying." << std::endl;
    o << std::endl;
    o << "      If you add terms to a covered work in accord with this section, you" << std::endl;
    o << "    must place, in the relevant source files, a statement of the" << std::endl;
    o << "    additional terms that apply to those files, or a notice indicating" << std::endl;
    o << "    where to find the applicable terms." << std::endl;
    o << std::endl;
    o << "      Additional terms, permissive or non-permissive, may be stated in the" << std::endl;
    o << "    form of a separately written license, or stated as exceptions;" << std::endl;
    o << "    the above requirements apply either way." << std::endl;
    o << std::endl;
    o << "      8. Termination." << std::endl;
    o << std::endl;
    o << "      You may not propagate or modify a covered work except as expressly" << std::endl;
    o << "    provided under this License.  Any attempt otherwise to propagate or" << std::endl;
    o << "    modify it is void, and will automatically terminate your rights under" << std::endl;
    o << "    this License (including any patent licenses granted under the third" << std::endl;
    o << "    paragraph of section 11)." << std::endl;
    o << std::endl;
    o << "      However, if you cease all violation of this License, then your" << std::endl;
    o << "    license from a particular copyright holder is reinstated (a)" << std::endl;
    o << "    provisionally, unless and until the copyright holder explicitly and" << std::endl;
    o << "    finally terminates your license, and (b) permanently, if the copyright" << std::endl;
    o << "    holder fails to notify you of the violation by some reasonable means" << std::endl;
    o << "    prior to 60 days after the cessation." << std::endl;
    o << std::endl;
    o << "      Moreover, your license from a particular copyright holder is" << std::endl;
    o << "    reinstated permanently if the copyright holder notifies you of the" << std::endl;
    o << "    violation by some reasonable means, this is the first time you have" << std::endl;
    o << "    received notice of violation of this License (for any work) from that" << std::endl;
    o << "    copyright holder, and you cure the violation prior to 30 days after" << std::endl;
    o << "    your receipt of the notice." << std::endl;
    o << std::endl;
    o << "      Termination of your rights under this section does not terminate the" << std::endl;
    o << "    licenses of parties who have received copies or rights from you under" << std::endl;
    o << "    this License.  If your rights have been terminated and not permanently" << std::endl;
    o << "    reinstated, you do not qualify to receive new licenses for the same" << std::endl;
    o << "    material under section 10." << std::endl;
    o << std::endl;
    o << "      9. Acceptance Not Required for Having Copies." << std::endl;
    o << std::endl;
    o << "      You are not required to accept this License in order to receive or" << std::endl;
    o << "    run a copy of the Program.  Ancillary propagation of a covered work" << std::endl;
    o << "    occurring solely as a consequence of using peer-to-peer transmission" << std::endl;
    o << "    to receive a copy likewise does not require acceptance.  However," << std::endl;
    o << "    nothing other than this License grants you permission to propagate or" << std::endl;
    o << "    modify any covered work.  These actions infringe copyright if you do" << std::endl;
    o << "    not accept this License.  Therefore, by modifying or propagating a" << std::endl;
    o << "    covered work, you indicate your acceptance of this License to do so." << std::endl;
    o << std::endl;
    o << "      10. Automatic Licensing of Downstream Recipients." << std::endl;
    o << std::endl;
    o << "      Each time you convey a covered work, the recipient automatically" << std::endl;
    o << "    receives a license from the original licensors, to run, modify and" << std::endl;
    o << "    propagate that work, subject to this License.  You are not responsible" << std::endl;
    o << "    for enforcing compliance by third parties with this License." << std::endl;
    o << std::endl;
    o << "      An \"entity transaction\" is a transaction transferring control of an" << std::endl;
    o << "    organization, or substantially all assets of one, or subdividing an" << std::endl;
    o << "    organization, or merging organizations.  If propagation of a covered" << std::endl;
    o << "    work results from an entity transaction, each party to that" << std::endl;
    o << "    transaction who receives a copy of the work also receives whatever" << std::endl;
    o << "    licenses to the work the party's predecessor in interest had or could" << std::endl;
    o << "    give under the previous paragraph, plus a right to possession of the" << std::endl;
    o << "    Corresponding Source of the work from the predecessor in interest, if" << std::endl;
    o << "    the predecessor has it or can get it with reasonable efforts." << std::endl;
    o << std::endl;
    o << "      You may not impose any further restrictions on the exercise of the" << std::endl;
    o << "    rights granted or affirmed under this License.  For example, you may" << std::endl;
    o << "    not impose a license fee, royalty, or other charge for exercise of" << std::endl;
    o << "    rights granted under this License, and you may not initiate litigation" << std::endl;
    o << "    (including a cross-claim or counterclaim in a lawsuit) alleging that" << std::endl;
    o << "    any patent claim is infringed by making, using, selling, offering for" << std::endl;
    o << "    sale, or importing the Program or any portion of it." << std::endl;
    o << std::endl;
    o << "      11. Patents." << std::endl;
    o << std::endl;
    o << "      A \"contributor\" is a copyright holder who authorizes use under this" << std::endl;
    o << "    License of the Program or a work on which the Program is based.  The" << std::endl;
    o << "    work thus licensed is called the contributor's \"contributor version\"." << std::endl;
    o << std::endl;
    o << "      A contributor's \"essential patent claims\" are all patent claims" << std::endl;
    o << "    owned or controlled by the contributor, whether already acquired or" << std::endl;
    o << "    hereafter acquired, that would be infringed by some manner, permitted" << std::endl;
    o << "    by this License, of making, using, or selling its contributor version," << std::endl;
    o << "    but do not include claims that would be infringed only as a" << std::endl;
    o << "    consequence of further modification of the contributor version.  For" << std::endl;
    o << "    purposes of this definition, \"control\" includes the right to grant" << std::endl;
    o << "    patent sublicenses in a manner consistent with the requirements of" << std::endl;
    o << "    this License." << std::endl;
    o << std::endl;
    o << "      Each contributor grants you a non-exclusive, worldwide, royalty-free" << std::endl;
    o << "    patent license under the contributor's essential patent claims, to" << std::endl;
    o << "    make, use, sell, offer for sale, import and otherwise run, modify and" << std::endl;
    o << "    propagate the contents of its contributor version." << std::endl;
    o << std::endl;
    o << "      In the following three paragraphs, a \"patent license\" is any express" << std::endl;
    o << "    agreement or commitment, however denominated, not to enforce a patent" << std::endl;
    o << "    (such as an express permission to practice a patent or covenant not to" << std::endl;
    o << "    sue for patent infringement).  To \"grant\" such a patent license to a" << std::endl;
    o << "    party means to make such an agreement or commitment not to enforce a" << std::endl;
    o << "    patent against the party." << std::endl;
    o << std::endl;
    o << "      If you convey a covered work, knowingly relying on a patent license," << std::endl;
    o << "    and the Corresponding Source of the work is not available for anyone" << std::endl;
    o << "    to copy, free of charge and under the terms of this License, through a" << std::endl;
    o << "    publicly available network server or other readily accessible means," << std::endl;
    o << "    then you must either (1) cause the Corresponding Source to be so" << std::endl;
    o << "    available, or (2) arrange to deprive yourself of the benefit of the" << std::endl;
    o << "    patent license for this particular work, or (3) arrange, in a manner" << std::endl;
    o << "    consistent with the requirements of this License, to extend the patent" << std::endl;
    o << "    license to downstream recipients.  \"Knowingly relying\" means you have" << std::endl;
    o << "    actual knowledge that, but for the patent license, your conveying the" << std::endl;
    o << "    covered work in a country, or your recipient's use of the covered work" << std::endl;
    o << "    in a country, would infringe one or more identifiable patents in that" << std::endl;
    o << "    country that you have reason to believe are valid." << std::endl;
    o << std::endl;
    o << "      If, pursuant to or in connection with a single transaction or" << std::endl;
    o << "    arrangement, you convey, or propagate by procuring conveyance of, a" << std::endl;
    o << "    covered work, and grant a patent license to some of the parties" << std::endl;
    o << "    receiving the covered work authorizing them to use, propagate, modify" << std::endl;
    o << "    or convey a specific copy of the covered work, then the patent license" << std::endl;
    o << "    you grant is automatically extended to all recipients of the covered" << std::endl;
    o << "    work and works based on it." << std::endl;
    o << std::endl;
    o << "      A patent license is \"discriminatory\" if it does not include within" << std::endl;
    o << "    the scope of its coverage, prohibits the exercise of, or is" << std::endl;
    o << "    conditioned on the non-exercise of one or more of the rights that are" << std::endl;
    o << "    specifically granted under this License.  You may not convey a covered" << std::endl;
    o << "    work if you are a party to an arrangement with a third party that is" << std::endl;
    o << "    in the business of distributing software, under which you make payment" << std::endl;
    o << "    to the third party based on the extent of your activity of conveying" << std::endl;
    o << "    the work, and under which the third party grants, to any of the" << std::endl;
    o << "    parties who would receive the covered work from you, a discriminatory" << std::endl;
    o << "    patent license (a) in connection with copies of the covered work" << std::endl;
    o << "    conveyed by you (or copies made from those copies), or (b) primarily" << std::endl;
    o << "    for and in connection with specific products or compilations that" << std::endl;
    o << "    contain the covered work, unless you entered into that arrangement," << std::endl;
    o << "    or that patent license was granted, prior to 28 March 2007." << std::endl;
    o << std::endl;
    o << "      Nothing in this License shall be construed as excluding or limiting" << std::endl;
    o << "    any implied license or other defenses to infringement that may" << std::endl;
    o << "    otherwise be available to you under applicable patent law." << std::endl;
    o << std::endl;
    o << "      12. No Surrender of Others' Freedom." << std::endl;
    o << std::endl;
    o << "      If conditions are imposed on you (whether by court order, agreement or" << std::endl;
    o << "    otherwise) that contradict the conditions of this License, they do not" << std::endl;
    o << "    excuse you from the conditions of this License.  If you cannot convey a" << std::endl;
    o << "    covered work so as to satisfy simultaneously your obligations under this" << std::endl;
    o << "    License and any other pertinent obligations, then as a consequence you may" << std::endl;
    o << "    not convey it at all.  For example, if you agree to terms that obligate you" << std::endl;
    o << "    to collect a royalty for further conveying from those to whom you convey" << std::endl;
    o << "    the Program, the only way you could satisfy both those terms and this" << std::endl;
    o << "    License would be to refrain entirely from conveying the Program." << std::endl;
    o << std::endl;
    o << "      13. Use with the GNU Affero General Public License." << std::endl;
    o << std::endl;
    o << "      Notwithstanding any other provision of this License, you have" << std::endl;
    o << "    permission to link or combine any covered work with a work licensed" << std::endl;
    o << "    under version 3 of the GNU Affero General Public License into a single" << std::endl;
    o << "    combined work, and to convey the resulting work.  The terms of this" << std::endl;
    o << "    License will continue to apply to the part which is the covered work," << std::endl;
    o << "    but the special requirements of the GNU Affero General Public License," << std::endl;
    o << "    section 13, concerning interaction through a network will apply to the" << std::endl;
    o << "    combination as such." << std::endl;
    o << std::endl;
    o << "      14. Revised Versions of this License." << std::endl;
    o << std::endl;
    o << "      The Free Software Foundation may publish revised and/or new versions of" << std::endl;
    o << "    the GNU General Public License from time to time.  Such new versions will" << std::endl;
    o << "    be similar in spirit to the present version, but may differ in detail to" << std::endl;
    o << "    address new problems or concerns." << std::endl;
    o << std::endl;
    o << "      Each version is given a distinguishing version number.  If the" << std::endl;
    o << "    Program specifies that a certain numbered version of the GNU General" << std::endl;
    o << "    Public License \"or any later version\" applies to it, you have the" << std::endl;
    o << "    option of following the terms and conditions either of that numbered" << std::endl;
    o << "    version or of any later version published by the Free Software" << std::endl;
    o << "    Foundation.  If the Program does not specify a version number of the" << std::endl;
    o << "    GNU General Public License, you may choose any version ever published" << std::endl;
    o << "    by the Free Software Foundation." << std::endl;
    o << std::endl;
    o << "      If the Program specifies that a proxy can decide which future" << std::endl;
    o << "    versions of the GNU General Public License can be used, that proxy's" << std::endl;
    o << "    public statement of acceptance of a version permanently authorizes you" << std::endl;
    o << "    to choose that version for the Program." << std::endl;
    o << std::endl;
    o << "      Later license versions may give you additional or different" << std::endl;
    o << "    permissions.  However, no additional obligations are imposed on any" << std::endl;
    o << "    author or copyright holder as a result of your choosing to follow a" << std::endl;
    o << "    later version." << std::endl;
    o << std::endl;
    o << "      15. Disclaimer of Warranty." << std::endl;
    o << std::endl;
    o << "      THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY" << std::endl;
    o << "    APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT" << std::endl;
    o << "    HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY" << std::endl;
    o << "    OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO," << std::endl;
    o << "    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR" << std::endl;
    o << "    PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM" << std::endl;
    o << "    IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF" << std::endl;
    o << "    ALL NECESSARY SERVICING, REPAIR OR CORRECTION." << std::endl;
    o << std::endl;
    o << "      16. Limitation of Liability." << std::endl;
    o << std::endl;
    o << "      IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING" << std::endl;
    o << "    WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS" << std::endl;
    o << "    THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY" << std::endl;
    o << "    GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE" << std::endl;
    o << "    USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF" << std::endl;
    o << "    DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD" << std::endl;
    o << "    PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS)," << std::endl;
    o << "    EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF" << std::endl;
    o << "    SUCH DAMAGES." << std::endl;
    o << std::endl;
    o << "      17. Interpretation of Sections 15 and 16." << std::endl;
    o << std::endl;
    o << "      If the disclaimer of warranty and limitation of liability provided" << std::endl;
    o << "    above cannot be given local legal effect according to their terms," << std::endl;
    o << "    reviewing courts shall apply local law that most closely approximates" << std::endl;
    o << "    an absolute waiver of all civil liability in connection with the" << std::endl;
    o << "    Program, unless a warranty or assumption of liability accompanies a" << std::endl;
    o << "    copy of the Program in return for a fee." << std::endl;
    o << std::endl;
    o << "                         END OF TERMS AND CONDITIONS" << std::endl;
    o << std::endl;
    o << "                How to Apply These Terms to Your New Programs" << std::endl;
    o << std::endl;
    o << "      If you develop a new program, and you want it to be of the greatest" << std::endl;
    o << "    possible use to the public, the best way to achieve this is to make it" << std::endl;
    o << "    free software which everyone can redistribute and change under these terms." << std::endl;
    o << std::endl;
    o << "      To do so, attach the following notices to the program.  It is safest" << std::endl;
    o << "    to attach them to the start of each source file to most effectively" << std::endl;
    o << "    state the exclusion of warranty; and each file should have at least" << std::endl;
    o << "    the \"copyright\" line and a pointer to where the full notice is found." << std::endl;
    o << std::endl;
    o << "        <one line to give the program's name and a brief idea of what it does.>" << std::endl;
    o << "        Copyright (C) <year>  <name of author>" << std::endl;
    o << std::endl;
    o << "        This program is free software: you can redistribute it and/or modify" << std::endl;
    o << "        it under the terms of the GNU General Public License as published by" << std::endl;
    o << "        the Free Software Foundation, either version 3 of the License, or" << std::endl;
    o << "        (at your option) any later version." << std::endl;
    o << std::endl;
    o << "        This program is distributed in the hope that it will be useful," << std::endl;
    o << "        but WITHOUT ANY WARRANTY; without even the implied warranty of" << std::endl;
    o << "        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the" << std::endl;
    o << "        GNU General Public License for more details." << std::endl;
    o << std::endl;
    o << "        You should have received a copy of the GNU General Public License" << std::endl;
    o << "        along with this program.  If not, see <https://www.gnu.org/licenses/>." << std::endl;
    o << std::endl;
    o << "    Also add information on how to contact you by electronic and paper mail." << std::endl;
    o << std::endl;
    o << "      If the program does terminal interaction, make it output a short" << std::endl;
    o << "    notice like this when it starts in an interactive mode:" << std::endl;
    o << std::endl;
    o << "        <program>  Copyright (C) <year>  <name of author>" << std::endl;
    o << "        This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'." << std::endl;
    o << "        This is free software, and you are welcome to redistribute it" << std::endl;
    o << "        under certain conditions; type `show c' for details." << std::endl;
    o << std::endl;
    o << "    The hypothetical commands `show w' and `show c' should show the appropriate" << std::endl;
    o << "    parts of the General Public License.  Of course, your program's commands" << std::endl;
    o << "    might be different; for a GUI interface, you would use an \"about box\"." << std::endl;
    o << std::endl;
    o << "      You should also get your employer (if you work as a programmer) or school," << std::endl;
    o << "    if any, to sign a \"copyright disclaimer\" for the program, if necessary." << std::endl;
    o << "    For more information on this, and how to apply and follow the GNU GPL, see" << std::endl;
    o << "    <https://www.gnu.org/licenses/>." << std::endl;
    o << std::endl;
    o << "      The GNU General Public License does not permit incorporating your program" << std::endl;
    o << "    into proprietary programs.  If your program is a subroutine library, you" << std::endl;
    o << "    may consider it more useful to permit linking proprietary applications with" << std::endl;
    o << "    the library.  If this is what you want to do, use the GNU Lesser General" << std::endl;
    o << "    Public License instead of this License.  But first, please read" << std::endl;
    o << "    <https://www.gnu.org/licenses/why-not-lgpl.html>." << std::endl;
}
