on:
  push:
    branches: [ "main", "development" ]
  pull_request:
name: Flatpak_test
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2

    - name: Git config
      run: git config --global --add safe.directory /__w/stdin_to_modbus_shm/stdin_to_modbus_shm

    - name: Init submodules
      run: git submodule init
      
    - name: Update submodules
      run: git submodule update

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: test_stdin-to-modbus-shm.flatpak
        manifest-path: network.koesling.test-stdin-to-modbus-shm.yml
        cache-key: flatpak-builder-${{ github.sha }}